"use client";

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Form from "./components/Form/Form";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import Image from "next/image";
import hashtag from "../../public/hashtag.png";
import money from "../../public/money.png";
import xelement from "../../public/xelement.png";
import metro from "../../public/metro.png";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-screen h-screen flex flex-col">
        <ToastContainer />
        <NextUIProvider>
          <Header />
          <Image
            src={hashtag}
            alt="hashtag"
            className="absolute left-4 top-20 z-10"
          />
          <Image
            src={metro}
            alt="metro"
            className="absolute right-0 top-0 bottom-0 h-full object-cover"
          />
          <Image
            src={money}
            alt="money icon"
            className="absolute top-20 right-[560px]"
          />
          <Image
            src={xelement}
            alt="xelement"
            className="absolute bottom-24 right-[740px]"
          />
          <div
            className="relative z-40 w-screen flex-1 bg-noise-effect flex items-center justify-center"
            style={{ minHeight: "calc(100vh - 236px)" }}
          >
            {children}
          </div>
          <Footer />
        </NextUIProvider>
      </body>
    </html>
  );
}
